import type { Topic } from "./types";

export const initialTopics: Topic[] = [
  {
    id: "ai-agents",
    title: "生成AI・AIエージェント活用",
    category: "AI",
    status: "学習中",
    understanding: 2,
    nextAction: "AIエージェントの仕組みと代表的なユースケースを30分で整理する",
    careerValue: "AIツールを安全に業務へ組み込める人材は、開発・業務改善の両方で評価されやすい。",
    accent: "#2563eb",
    tasks: [
      { id: "ai-1", title: "LLM、ツール利用、メモリ、プランニングの違いを説明できる", done: true },
      { id: "ai-2", title: "AIエージェントの業務ユースケースを3つ書き出す", done: false },
      { id: "ai-3", title: "人間の承認が必要な場面を整理する", done: false },
      { id: "ai-4", title: "小さな自動化フローを設計する", done: false },
    ],
  },
  {
    id: "context-engineering",
    title: "プロンプト / コンテキストエンジニアリング",
    category: "AI",
    status: "学習中",
    understanding: 2,
    nextAction: "良い入力・悪い入力の例を比較して、再利用できる指示テンプレートを作る",
    careerValue: "AIの出力品質を安定させる力は、開発・分析・ドキュメント作成で直接役立つ。",
    accent: "#0f766e",
    tasks: [
      { id: "ce-1", title: "目的、制約、入力データ、出力形式を分けて書ける", done: true },
      { id: "ce-2", title: "RAGと長文コンテキストの使い分けを理解する", done: false },
      { id: "ce-3", title: "評価観点をプロンプトに含められる", done: false },
      { id: "ce-4", title: "トークンコストを意識した設計ができる", done: false },
    ],
  },
  {
    id: "ai-security",
    title: "AIセキュリティ・ガバナンス",
    category: "Security",
    status: "未着手",
    understanding: 1,
    nextAction: "プロンプトインジェクション、情報漏えい、権限管理の基本リスクを確認する",
    careerValue: "AI導入が進むほど、セキュリティと監査を説明できる人材の価値が高まる。",
    accent: "#dc2626",
    tasks: [
      { id: "ais-1", title: "プロンプトインジェクションの例を説明できる", done: false },
      { id: "ais-2", title: "AIに渡してはいけない情報を分類できる", done: false },
      { id: "ais-3", title: "監査ログと人間の承認フローの必要性を説明できる", done: false },
      { id: "ais-4", title: "社内利用ルールのドラフトを作る", done: false },
    ],
  },
  {
    id: "web-typescript-api",
    title: "Web基礎・TypeScript・API設計",
    category: "Web",
    status: "復習中",
    understanding: 3,
    nextAction: "HTTPメソッドとREST APIの設計例を、自分の言葉でまとめる",
    careerValue: "フロントエンド、バックエンド、クラウドの土台になるため、転職課題でも出題されやすい。",
    accent: "#7c3aed",
    tasks: [
      { id: "web-1", title: "HTML、CSS、JavaScriptの役割を説明できる", done: true },
      { id: "web-2", title: "TypeScriptの型注釈とユニオン型を使える", done: true },
      { id: "web-3", title: "HTTPステータスコードの代表例を理解する", done: false },
      { id: "web-4", title: "簡単なCRUD API仕様を書ける", done: false },
    ],
  },
  {
    id: "cloud-kubernetes",
    title: "クラウド基礎・Docker・Kubernetes",
    category: "Cloud",
    status: "学習中",
    understanding: 2,
    nextAction: "コンテナ、イメージ、Pod、Serviceの関係を図にして覚える",
    careerValue: "AWS、Azure、GCPやCKA/CKAD系の資格学習につながり、インフラ職にも開発職にも効く。",
    accent: "#0891b2",
    tasks: [
      { id: "ck-1", title: "IaaS、PaaS、SaaSの違いを説明できる", done: true },
      { id: "ck-2", title: "Dockerfileの基本命令を理解する", done: false },
      { id: "ck-3", title: "Kubernetesの主要リソースを説明できる", done: false },
      { id: "ck-4", title: "クラウドの責任共有モデルを理解する", done: false },
    ],
  },
  {
    id: "devops-platform",
    title: "DevOps / CI/CD / プラットフォームエンジニアリング",
    category: "Delivery",
    status: "未着手",
    understanding: 1,
    nextAction: "GitHub Actionsの基本ワークフローを読んで、ビルドからテストまでの流れを見る",
    careerValue: "開発チームの生産性改善に直結し、実務経験として語りやすいテーマ。",
    accent: "#ea580c",
    tasks: [
      { id: "dp-1", title: "CIとCDの違いを説明できる", done: false },
      { id: "dp-2", title: "テスト自動化の価値を説明できる", done: false },
      { id: "dp-3", title: "IaCの基本概念を理解する", done: false },
      { id: "dp-4", title: "開発者体験を改善する仕組みを1つ提案する", done: false },
    ],
  },
  {
    id: "zero-trust",
    title: "サイバーセキュリティ基礎・ゼロトラスト",
    category: "Security",
    status: "未着手",
    understanding: 1,
    nextAction: "認証、認可、多要素認証、最小権限をセットで復習する",
    careerValue: "基本情報、情報処理安全確保支援士、クラウド資格のどれにも接続しやすい。",
    accent: "#be123c",
    tasks: [
      { id: "zt-1", title: "認証と認可の違いを説明できる", done: false },
      { id: "zt-2", title: "代表的な攻撃手法を3つ説明できる", done: false },
      { id: "zt-3", title: "ゼロトラストの考え方を説明できる", done: false },
      { id: "zt-4", title: "ログ監視とインシデント対応の流れを理解する", done: false },
    ],
  },
  {
    id: "observability-sre",
    title: "オブザーバビリティ / SRE",
    category: "Operations",
    status: "未着手",
    understanding: 1,
    nextAction: "ログ、メトリクス、トレースの違いと使いどころを整理する",
    careerValue: "運用改善や障害対応を説明できると、実務寄りの強みとして伝えやすい。",
    accent: "#4d7c0f",
    tasks: [
      { id: "obs-1", title: "ログ、メトリクス、トレースを区別できる", done: false },
      { id: "obs-2", title: "SLI、SLO、SLAの違いを説明できる", done: false },
      { id: "obs-3", title: "障害対応の基本フローを理解する", done: false },
      { id: "obs-4", title: "ダッシュボードで見るべき指標を選べる", done: false },
    ],
  },
  {
    id: "data-rag-vector",
    title: "データ基盤・RAG・ベクトル検索",
    category: "Data",
    status: "未着手",
    understanding: 1,
    nextAction: "RAGの検索、生成、評価の流れを1枚メモにまとめる",
    careerValue: "AIアプリ開発で需要が高く、データエンジニアリングとアプリ開発をつなげられる。",
    accent: "#b45309",
    tasks: [
      { id: "data-1", title: "構造化データと非構造化データを説明できる", done: false },
      { id: "data-2", title: "埋め込みとベクトル検索の概要を理解する", done: false },
      { id: "data-3", title: "RAGの基本構成を説明できる", done: false },
      { id: "data-4", title: "回答品質を評価する観点を3つ挙げる", done: false },
    ],
  },
];
